// GENERATED by tools/build-media.py — do not edit by hand.
// Widths that exist on disk for each image stem.
export const MEDIA_WIDTHS: Record<string, number[]> = {
  'farm-day': [480, 768, 1200, 1800, 2400],
  'farm-dusk': [480, 768, 1200, 1800, 2400],
  'farm-solar': [480, 768, 1200],
  'hero-poster': [480, 768],
  'logistics-gate': [480, 768, 1200, 1800, 2400],
  'logistics-trucks': [480, 768, 1200, 1800, 2400],
  'stage-3-grading-poster': [480, 768],
};
